# Generated by Django 3.1 on 2025-02-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('TarefaId', models.AutoField(primary_key=True, serialize=False)),
                ('TarefaNome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('UsuarioId', models.AutoField(primary_key=True, serialize=False)),
                ('UsuarioNomme', models.CharField(max_length=100)),
                ('Departamento', models.CharField(max_length=100)),
                ('DataDeIngresso', models.DateField()),
                ('ArquivoDeFoto', models.CharField(max_length=100)),
            ],
        ),
    ]
