# Generated by Django 3.1 on 2025-02-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='UsuarioNomme',
            new_name='UsuarioNome',
        ),
    ]
