# Generated by Django 3.1 on 2025-02-10 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UsuarioApp', '0002_auto_20250206_1519'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AddField(
            model_name='tarefas',
            name='TarefaConcluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefas',
            name='TarefaDescricao',
            field=models.CharField(default='Sem descrição', max_length=1000),
        ),
    ]
